department_names = [
    "Civil and Environmental Engineering",
    "Mechanical Engineering",
    "Materials Science and Engineering",
    "Architecture",
    "Chemistry",
    "Electrical Engineering and Computer Science",
    "Biology",
    "Physics",
    "Brain and Cognitive Sciences",
    "Chemical Engineering",
    "Urban Studies and Planning",
    "Earth, Atmospheric, and Planetary Sciences",
    "Economics",
    "Management",
    "Aeronautics and Astronautics",
    "Political Science",
    "Mathematics",
    "Biological Engineering",
    "Humanities",
    "Anthropology",
    "History",
    "Global Lanugages",
    "Literature",
    "Music and Theater Arts",
    "Writing",
    "Nuclear Science and Engineering",
    "Linguistics and Philosophy",
    "Aerospace Studies",
    "Concourse Program",
    "Comparative Media Studies",
    "Computational and Systems Biology",
    "Center for Computational Science and Engineering",
    "Chief Digital Officer",
    "Edgerton Center",
    "Engineering Management",
    "Experimental Study Group",
    "Health Sciences and Technology",
    "Institute for Data, Systems and Society",
    "Media Arts and Sciences",
    "Military Science",
    "Naval Science",
    "Supply Chain Management",
    "Special Program",
    "Science, Technology, and Society",
    "Women's and Gender Studies",
]
